#!/bin/sh
# vim: set filetype=sh

if [ -e "$HOME/.shell.path" ]; then
     source "$HOME/.shell.path"
fi

if [ -e "$HOME/.shell.env" ]; then
     source "$HOME/.shell.env"
fi

if [ -e "$HOME/.shell.aliases" ]; then
     source "$HOME/.shell.aliases"
fi

if [ -e "$HOME/.shell.functions" ]; then
     source "$HOME/.shell.functions"
fi


# if [ -x "$HOMEBREW_REPOSITORY/bin/nodenv" ]; then
#      eval "$(nodenv init -)"
# fi
# 
# if [ -x "$HOMEBREW_REPOSITORY/bin/exenv" ]; then
#      eval "$(exenv init -)"
# fi
