#!/bin/bash

# Requires the 1Password command line tool and jq:
#
# https://support.1password.com/command-line-getting-started/
# brew install jq

USERNAME=$USER
PID_FILE="/var/run/vpn-openconnect.pid"
OP_SESSION_SUFFIX="my"

op_session_var="OP_SESSION_${OP_SESSION_SUFFIX}"

OP_SESSION="${!op_session_var}"
OP_PASSWORD_NAME="Chicago VPN"

load_session () {
	OP_SESSION=$(op signin "$OP_SESSION_SUFFIX" --output=raw)

	if [ $? -eq 1 ]; then
		echo "Please sign in again."
		eval $(op signin $OP_SESSION_SUFFIX)

		OP_SESSION=$(op signin "$OP_SESSION_SUFFIX" --output=raw)
	fi
}

fetch_password () {
	echo "grabbing password $OP_PASSWORD_NAME from $OP_SESSION"
	password=$(op get item "$OP_PASSWORD_NAME" --session=$OP_SESSION | jq '.details.fields[] | select(.designation=="password").value')

	if [ $? -eq 1 ]; then
		echo "Please sign in again."
		load_session
		fetch_password
	fi
}

fetch_password

echo "Copying password to system pasteboard."
